### ISSUE TITLE
Tooltips don't get updated when switching layers if using movetips

### ISSUE THREAD

**Issue by ansis** [cutting-room-floor/map-site#14]
Tooltips don't switch to the new layer if you are using both movetips and tooltips.

A separate wax.mm.interaction() object is created for both movetips and tooltips, and the reference to the movetip one overwrites the tooltip one. This means the tooltips don't get updated when setting an overlay

**Comment by jdpowell** [comment]
What are movetips? Can I just get rid of them? I am pretty new at the interactions between the files.  I just found the links and code I needed to change in the html and edited it that way.

**Comment by ansis** [comment]
The movetips are the boxes that follow your mouse, the tooltips are the ones that stay in one spot. It looks like in your case its the movetips not getting updated.

If you only want one of them, remove the other from the _features_ array, found in the site configuration section of `index.html`.

**Comment by jdpowell** [comment]
And if I want them both, just have the tooltips overwrite the movetips or will that mess it up as well?

**Comment by ansis** [comment]
@jdpowell 

I've opened a pull request to fix this issue. If you want, you can try out the fix by replacing your script.js file with https://raw.github.com/mapbox/map-site/ad6226567a00382456a00694339687691c9e9207/script.js
