### ISSUE TITLE
active layout state and title alignment.

### ISSUE THREAD

**Issue by tristen** [cutting-room-floor/map-site#7]
I'd like to run a couple ideas before implementation

![](https://img.skitch.com/20120508-bp4sshdpkwjr5xjfet7srjqi8c.jpg)
1. I feel like the icon and title just doesn't sit right when entire site is fluid and the header is fixed aligned. This should remain 20px off the left side of the screen.
2. To make it clear the links at the top right alter the presentation of the layout I think the should be centered vertically and have an active button state implying which state is turned on.

**Comment by samanpwbb** [comment]
Tristen, don't worry about the html/css of this template. We're going to launch with the designs in the Twitter and Property branches, not this design. There isn't going to be a generic blank template that we release.
