### ISSUE TITLE
Persistent inline tooltips are broken 

### ISSUE THREAD

**Issue by samanpwbb** [cutting-room-floor/map-site#8]
Once triggered, persistent tooltips become absolute positioned, and don't move with the map: 
![](http://cl.ly/0o1l10411l210F3S1N0L/Screen%20Shot%202012-05-09%20at%2010.58.19%20AM.png)

Is there a way to make these move relative to the map, or should we disable persistence on click?

**Comment by dhcole** [comment]
I think we should just disable the click state. In fact, it should not be on in the first place. This may be a wax bug.

**Comment by dhcole** [comment]
Fixed by disabling click state in movetips.
